// === BANCO DE ALIMENTOS EXPANDIDO ===
// Valores por 100g (ou por unidade quando indicado)
const NT_FOODS_DB = [
  // === CARNES E PROTEÍNAS ===
  { name: "Peito de frango grelhado", cat: "prot", unit: "g", kcal: 159, prot: 32, carb: 0, fat: 3.2, default_qty: 150 },
  { name: "Coxa/sobrecoxa frango s/ pele", cat: "prot", unit: "g", kcal: 172, prot: 26, carb: 0, fat: 7.5, default_qty: 150 },
  { name: "Músculo bovino cozido", cat: "prot", unit: "g", kcal: 171, prot: 32, carb: 0, fat: 4.5, default_qty: 150 },
  { name: "Patinho bovino grelhado", cat: "prot", unit: "g", kcal: 166, prot: 32, carb: 0, fat: 4, default_qty: 150 },
  { name: "Acém bovino cozido", cat: "prot", unit: "g", kcal: 212, prot: 27, carb: 0, fat: 11, default_qty: 150 },
  { name: "Carne moída magra", cat: "prot", unit: "g", kcal: 164, prot: 26, carb: 0, fat: 6.5, default_qty: 150 },
  { name: "Fígado bovino acebolado", cat: "prot", unit: "g", kcal: 150, prot: 25, carb: 4, fat: 4, default_qty: 150 },
  { name: "Moela de frango cozida", cat: "prot", unit: "g", kcal: 130, prot: 22, carb: 0, fat: 4.5, default_qty: 150 },
  { name: "Carré (lombo suíno) grelhado", cat: "prot", unit: "g", kcal: 164, prot: 27, carb: 0, fat: 6, default_qty: 150 },
  { name: "Costela suína assada", cat: "prot", unit: "g", kcal: 290, prot: 20, carb: 0, fat: 23, default_qty: 100 },
  { name: "Tilápia grelhada", cat: "prot", unit: "g", kcal: 96, prot: 20, carb: 0, fat: 1.7, default_qty: 150 },
  { name: "Salmão grelhado", cat: "prot", unit: "g", kcal: 208, prot: 22, carb: 0, fat: 13, default_qty: 120 },
  { name: "Atum em lata (água)", cat: "prot", unit: "g", kcal: 116, prot: 26, carb: 0, fat: 1, default_qty: 80 },
  { name: "Sardinha em lata", cat: "prot", unit: "g", kcal: 208, prot: 25, carb: 0, fat: 12, default_qty: 80 },
  { name: "Camarão cozido", cat: "prot", unit: "g", kcal: 90, prot: 19, carb: 0, fat: 1.5, default_qty: 100 },
  { name: "Proteína de soja texturizada", cat: "prot", unit: "g", kcal: 330, prot: 50, carb: 22, fat: 1.5, default_qty: 30 },
  { name: "Tofu firme", cat: "prot", unit: "g", kcal: 76, prot: 8, carb: 2, fat: 4.5, default_qty: 100 },

  // === OVOS E LATICÍNIOS ===
  { name: "Ovo inteiro", cat: "prot", unit: "un", portion_g: 50, kcal: 146, prot: 13, carb: 0.6, fat: 10, default_qty: 3 },
  { name: "Clara de ovo", cat: "prot", unit: "un", portion_g: 33, kcal: 52, prot: 11, carb: 0.7, fat: 0.2, default_qty: 4 },
  { name: "Queijo muçarela (fatia)", cat: "lact", unit: "un", portion_g: 20, kcal: 300, prot: 22, carb: 1, fat: 23, default_qty: 1 },
  { name: "Queijo cottage", cat: "lact", unit: "g", kcal: 98, prot: 12, carb: 3, fat: 4.5, default_qty: 50 },
  { name: "Queijo prato (fatia)", cat: "lact", unit: "un", portion_g: 20, kcal: 360, prot: 23, carb: 0.5, fat: 29, default_qty: 1 },
  { name: "Requeijão cremoso", cat: "lact", unit: "g", kcal: 257, prot: 7, carb: 2, fat: 25, default_qty: 30 },
  { name: "Iogurte natural desnatado", cat: "lact", unit: "g", kcal: 42, prot: 4, carb: 5.5, fat: 0.2, default_qty: 170 },
  { name: "Iogurte grego zero", cat: "lact", unit: "un", portion_g: 100, kcal: 55, prot: 9, carb: 4, fat: 0.3, default_qty: 1 },
  { name: "Leite desnatado líquido", cat: "lact", unit: "ml", kcal: 35, prot: 3.4, carb: 5, fat: 0.1, default_qty: 200 },
  { name: "Leite integral", cat: "lact", unit: "ml", kcal: 60, prot: 3, carb: 4.7, fat: 3.2, default_qty: 200 },
  { name: "Leite em pó desnatado (colher)", cat: "lact", unit: "un", portion_g: 10, kcal: 360, prot: 36, carb: 52, fat: 0.5, default_qty: 3 },
  { name: "Whey Protein (scoop)", cat: "supl", unit: "un", portion_g: 30, kcal: 400, prot: 80, carb: 7, fat: 3, default_qty: 1 },
  { name: "Albumina (colher)", cat: "supl", unit: "un", portion_g: 20, kcal: 360, prot: 80, carb: 4, fat: 0.5, default_qty: 1 },
  { name: "Creatina (colher)", cat: "supl", unit: "un", portion_g: 5, kcal: 0, prot: 0, carb: 0, fat: 0, default_qty: 1 },

  // === CARBOIDRATOS ===
  { name: "Cuscuz de milho (cozido)", cat: "carb", unit: "g", kcal: 112, prot: 2.5, carb: 25, fat: 0.3, default_qty: 150 },
  { name: "Arroz branco cozido", cat: "carb", unit: "g", kcal: 128, prot: 2.5, carb: 28, fat: 0.2, default_qty: 100 },
  { name: "Arroz integral cozido", cat: "carb", unit: "g", kcal: 124, prot: 2.6, carb: 26, fat: 1, default_qty: 100 },
  { name: "Batata doce cozida", cat: "carb", unit: "g", kcal: 77, prot: 1.3, carb: 18, fat: 0.1, default_qty: 150 },
  { name: "Batata inglesa cozida", cat: "carb", unit: "g", kcal: 52, prot: 1.2, carb: 12, fat: 0.1, default_qty: 150 },
  { name: "Mandioca cozida", cat: "carb", unit: "g", kcal: 125, prot: 0.6, carb: 30, fat: 0.3, default_qty: 100 },
  { name: "Inhame cozido", cat: "carb", unit: "g", kcal: 97, prot: 2, carb: 23, fat: 0.1, default_qty: 100 },
  { name: "Macarrão cozido", cat: "carb", unit: "g", kcal: 102, prot: 3.5, carb: 20, fat: 0.5, default_qty: 100 },
  { name: "Pão francês", cat: "carb", unit: "un", portion_g: 50, kcal: 300, prot: 9, carb: 58, fat: 3, default_qty: 1 },
  { name: "Pão integral (fatia)", cat: "carb", unit: "un", portion_g: 25, kcal: 253, prot: 9, carb: 44, fat: 4, default_qty: 2 },
  { name: "Tapioca (goma hidratada)", cat: "carb", unit: "g", kcal: 68, prot: 0, carb: 17, fat: 0, default_qty: 50 },
  { name: "Aveia em flocos", cat: "carb", unit: "g", kcal: 366, prot: 14, carb: 60, fat: 7, default_qty: 30 },
  { name: "Granola", cat: "carb", unit: "g", kcal: 421, prot: 10, carb: 64, fat: 15, default_qty: 30 },
  { name: "Feijão carioca cozido", cat: "carb", unit: "g", kcal: 76, prot: 4.8, carb: 13.6, fat: 0.5, default_qty: 100 },
  { name: "Feijão preto cozido", cat: "carb", unit: "g", kcal: 77, prot: 4.5, carb: 14, fat: 0.5, default_qty: 100 },
  { name: "Lentilha cozida", cat: "carb", unit: "g", kcal: 93, prot: 6.3, carb: 16, fat: 0.4, default_qty: 100 },
  { name: "Grão de bico cozido", cat: "carb", unit: "g", kcal: 130, prot: 6.7, carb: 18, fat: 2.5, default_qty: 100 },

  // === FRUTAS ===
  { name: "Banana", cat: "fruta", unit: "un", portion_g: 100, kcal: 89, prot: 1.1, carb: 23, fat: 0.3, default_qty: 1 },
  { name: "Maçã", cat: "fruta", unit: "un", portion_g: 150, kcal: 52, prot: 0.3, carb: 14, fat: 0.2, default_qty: 1 },
  { name: "Laranja", cat: "fruta", unit: "un", portion_g: 150, kcal: 47, prot: 0.9, carb: 12, fat: 0.1, default_qty: 1 },
  { name: "Melancia", cat: "fruta", unit: "g", kcal: 30, prot: 0.6, carb: 7.5, fat: 0.2, default_qty: 250 },
  { name: "Mamão", cat: "fruta", unit: "g", kcal: 40, prot: 0.5, carb: 10, fat: 0.1, default_qty: 200 },
  { name: "Morango", cat: "fruta", unit: "g", kcal: 32, prot: 0.7, carb: 7.7, fat: 0.3, default_qty: 150 },
  { name: "Manga", cat: "fruta", unit: "g", kcal: 60, prot: 0.8, carb: 15, fat: 0.4, default_qty: 150 },
  { name: "Abacaxi", cat: "fruta", unit: "g", kcal: 48, prot: 0.5, carb: 12, fat: 0.1, default_qty: 150 },
  { name: "Uva", cat: "fruta", unit: "g", kcal: 69, prot: 0.7, carb: 18, fat: 0.2, default_qty: 100 },
  { name: "Pera", cat: "fruta", unit: "un", portion_g: 150, kcal: 57, prot: 0.4, carb: 15, fat: 0.1, default_qty: 1 },
  { name: "Melão", cat: "fruta", unit: "g", kcal: 34, prot: 0.8, carb: 8, fat: 0.2, default_qty: 200 },
  { name: "Abacate", cat: "fruta", unit: "g", kcal: 160, prot: 2, carb: 8.5, fat: 15, default_qty: 50 },
  { name: "Açaí (polpa pura)", cat: "fruta", unit: "g", kcal: 58, prot: 0.8, carb: 6, fat: 3.5, default_qty: 100 },
  { name: "Kiwi", cat: "fruta", unit: "un", portion_g: 75, kcal: 61, prot: 1.1, carb: 15, fat: 0.5, default_qty: 1 },

  // === LEGUMES E VERDURAS ===
  { name: "Brócolis cozido", cat: "veg", unit: "g", kcal: 35, prot: 2.4, carb: 7, fat: 0.4, default_qty: 100 },
  { name: "Abobrinha cozida", cat: "veg", unit: "g", kcal: 15, prot: 1, carb: 3, fat: 0.1, default_qty: 100 },
  { name: "Chuchu cozido", cat: "veg", unit: "g", kcal: 17, prot: 0.6, carb: 4, fat: 0.1, default_qty: 100 },
  { name: "Cenoura cozida", cat: "veg", unit: "g", kcal: 30, prot: 0.6, carb: 7, fat: 0.2, default_qty: 80 },
  { name: "Vagem cozida", cat: "veg", unit: "g", kcal: 25, prot: 1.5, carb: 5, fat: 0.2, default_qty: 100 },
  { name: "Espinafre cozido", cat: "veg", unit: "g", kcal: 23, prot: 2.9, carb: 3.6, fat: 0.3, default_qty: 80 },
  { name: "Tomate", cat: "veg", unit: "g", kcal: 18, prot: 0.9, carb: 3.9, fat: 0.2, default_qty: 100 },
  { name: "Alface", cat: "veg", unit: "g", kcal: 11, prot: 1, carb: 1.7, fat: 0.2, default_qty: 50 },
  { name: "Pepino", cat: "veg", unit: "g", kcal: 10, prot: 0.6, carb: 2, fat: 0.1, default_qty: 100 },
  { name: "Beterraba cozida", cat: "veg", unit: "g", kcal: 49, prot: 1.7, carb: 11, fat: 0.1, default_qty: 80 },
  { name: "Milho cozido (espiga)", cat: "veg", unit: "un", portion_g: 100, kcal: 96, prot: 3.2, carb: 19, fat: 1.4, default_qty: 1 },

  // === GORDURAS E OLEAGINOSAS ===
  { name: "Azeite de oliva (colher)", cat: "gord", unit: "un", portion_g: 8, kcal: 884, prot: 0, carb: 0, fat: 100, default_qty: 1 },
  { name: "Manteiga (colher)", cat: "gord", unit: "un", portion_g: 10, kcal: 717, prot: 0.9, carb: 0.1, fat: 81, default_qty: 1 },
  { name: "Pasta de amendoim", cat: "gord", unit: "g", kcal: 589, prot: 25, carb: 20, fat: 50, default_qty: 15 },
  { name: "Castanha do Pará", cat: "gord", unit: "un", portion_g: 4, kcal: 656, prot: 14, carb: 12, fat: 66, default_qty: 3 },
  { name: "Amendoim torrado", cat: "gord", unit: "g", kcal: 567, prot: 26, carb: 16, fat: 49, default_qty: 20 },
  { name: "Chia (colher)", cat: "gord", unit: "un", portion_g: 10, kcal: 486, prot: 17, carb: 42, fat: 31, default_qty: 1 },

  // === INDUSTRIALIZADOS / DOCES ===
  { name: "Chocolate meio amargo", cat: "doce", unit: "g", kcal: 530, prot: 5, carb: 60, fat: 30, default_qty: 20 },
  { name: "Chocolate ao leite", cat: "doce", unit: "g", kcal: 535, prot: 7, carb: 59, fat: 30, default_qty: 25 },
  { name: "Doce de leite", cat: "doce", unit: "g", kcal: 310, prot: 6, carb: 55, fat: 7, default_qty: 20 },
  { name: "Snickers (barra 45g)", cat: "doce", unit: "un", portion_g: 45, kcal: 489, prot: 9, carb: 60, fat: 24, default_qty: 1 },
  { name: "Trento (unidade)", cat: "doce", unit: "un", portion_g: 32, kcal: 406, prot: 4, carb: 56, fat: 19, default_qty: 1 },
  { name: "Bis (unidade)", cat: "doce", unit: "un", portion_g: 10, kcal: 530, prot: 6, carb: 60, fat: 30, default_qty: 2 },
  { name: "Paçoca (unidade)", cat: "doce", unit: "un", portion_g: 22, kcal: 470, prot: 14, carb: 46, fat: 27, default_qty: 1 },
  { name: "Sorvete massa", cat: "doce", unit: "g", kcal: 207, prot: 3.5, carb: 24, fat: 11, default_qty: 80 },
  { name: "Picolé frutas", cat: "doce", unit: "un", portion_g: 60, kcal: 80, prot: 0.3, carb: 20, fat: 0.1, default_qty: 1 },
  { name: "Waffle (unidade)", cat: "doce", unit: "un", portion_g: 35, kcal: 370, prot: 6, carb: 50, fat: 16, default_qty: 1 },
  { name: "Biscoito recheado (unidade)", cat: "doce", unit: "un", portion_g: 13, kcal: 480, prot: 5, carb: 67, fat: 21, default_qty: 3 },
  { name: "Biscoito cream cracker (unidade)", cat: "doce", unit: "un", portion_g: 8, kcal: 432, prot: 10, carb: 68, fat: 14, default_qty: 5 },
  { name: "Bolo simples", cat: "doce", unit: "g", kcal: 350, prot: 5, carb: 50, fat: 15, default_qty: 60 },
  { name: "Brigadeiro (unidade)", cat: "doce", unit: "un", portion_g: 20, kcal: 375, prot: 4, carb: 60, fat: 13, default_qty: 1 },
  { name: "Sonho de Valsa (unidade)", cat: "doce", unit: "un", portion_g: 23, kcal: 478, prot: 7, carb: 56, fat: 25, default_qty: 1 },
  { name: "Gelatina zero", cat: "doce", unit: "g", kcal: 6, prot: 1.5, carb: 0, fat: 0, default_qty: 100 },

  // === BEBIDAS ===
  { name: "Café preto (sem açúcar)", cat: "beb", unit: "ml", kcal: 2, prot: 0.1, carb: 0, fat: 0, default_qty: 100 },
  { name: "Refrigerante zero", cat: "beb", unit: "ml", kcal: 0, prot: 0, carb: 0, fat: 0, default_qty: 350 },
  { name: "Suco de laranja natural", cat: "beb", unit: "ml", kcal: 45, prot: 0.7, carb: 10, fat: 0.2, default_qty: 200 },
  { name: "Água de coco", cat: "beb", unit: "ml", kcal: 19, prot: 0.2, carb: 4.5, fat: 0.1, default_qty: 200 },
  { name: "Cerveja", cat: "beb", unit: "ml", kcal: 43, prot: 0.3, carb: 3.5, fat: 0, default_qty: 350 },
  { name: "Energético zero", cat: "beb", unit: "un", portion_g: 250, kcal: 4, prot: 0, carb: 0, fat: 0, default_qty: 1 },

  // === FAST FOOD / PRONTOS ===
  { name: "Pizza (fatia média)", cat: "fast", unit: "un", portion_g: 100, kcal: 266, prot: 11, carb: 33, fat: 10, default_qty: 1 },
  { name: "Hambúrguer artesanal", cat: "fast", unit: "un", portion_g: 200, kcal: 250, prot: 14, carb: 18, fat: 13, default_qty: 1 },
  { name: "Coxinha (unidade)", cat: "fast", unit: "un", portion_g: 80, kcal: 263, prot: 8, carb: 28, fat: 13, default_qty: 1 },
  { name: "Pão de queijo (unidade)", cat: "fast", unit: "un", portion_g: 25, kcal: 320, prot: 5, carb: 44, fat: 14, default_qty: 2 },
  { name: "Açaí com granola (copo)", cat: "fast", unit: "g", kcal: 150, prot: 1.5, carb: 25, fat: 5, default_qty: 200 },

  // === TEMPEROS / EXTRAS ===
  { name: "Açúcar (colher)", cat: "extra", unit: "un", portion_g: 5, kcal: 387, prot: 0, carb: 100, fat: 0, default_qty: 1 },
  { name: "Mel (colher)", cat: "extra", unit: "un", portion_g: 10, kcal: 304, prot: 0.3, carb: 82, fat: 0, default_qty: 1 },
  { name: "Ketchup (colher)", cat: "extra", unit: "un", portion_g: 15, kcal: 100, prot: 1, carb: 25, fat: 0.1, default_qty: 1 },
  { name: "Maionese (colher)", cat: "extra", unit: "un", portion_g: 12, kcal: 680, prot: 1, carb: 0.6, fat: 75, default_qty: 1 },
];

// Categorias para filtro
const NT_CATEGORIES = {
  all: "Todos",
  prot: "🥩 Proteínas",
  lact: "🧀 Laticínios",
  supl: "💊 Suplementos",
  carb: "🍚 Carboidratos",
  fruta: "🍎 Frutas",
  veg: "🥦 Legumes",
  gord: "🥜 Gorduras",
  doce: "🍫 Doces",
  beb: "☕ Bebidas",
  fast: "🍕 Prontos",
  extra: "🧂 Extras",
  custom: "⭐ Meus Alimentos"
};
